In [1]:
import numpy as np 
import pandas as pd
import sklearn

In [2]:
from sklearn.datasets import fetch_20newsgroups
news = fetch_20newsgroups()

In [3]:
print(news.keys())

dict_keys(['data', 'filenames', 'target_names', 'target', 'DESCR'])


In [8]:
news.target_names

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [15]:
cats = ['alt.atheism', 'soc.religion.christian','comp.graphics', 'sci.med']

In [11]:
from sklearn.feature_extraction.text import CountVectorizer
count_vector = CountVectorizer()

In [16]:
news_train=fetch_20newsgroups(subset='train',categories=cats)


In [17]:
news_test=fetch_20newsgroups(subset='test',categories=cats)

In [20]:
x_train=count_vector.fit_transform(news_train.data)
print(x_train.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [21]:
print(x_train.shape)

(2257, 35788)


In [24]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer=TfidfTransformer()
x_train_tfidf=tfidf_transformer.fit_transform(x_train)
x_train.shape

(2257, 35788)

In [27]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB().fit(x_train_tfidf,news_train.target)

# test the model

In [28]:
x_test_df=count_vector.transform(news_test.data)
x_test_tfidf=tfidf_transformer.fit_transform(x_test_df)
pred=model.predict(x_test_tfidf)
print(pred)

[2 2 3 ... 2 2 1]
